services:
  flood:
    hostname: flood
    image: jesec/flood
    user: 1000:1001
    restart: unless-stopped
    command: --port 3001 --allowedpath /data
    environment:
      HOME: /config
    volumes:
      - /home/jc/dlconfig:/config
      - /mnt/data0:/data
    ports:
      - 127.0.0.1:3001:3001
