services:
  flood:
    hostname: flood
    image: jesec/flood
    user: 1000:1001
    restart: unless-stopped
    command: --port 3001 --allowedpath /data
    environment:
      HOME: /config
    volumes:
      - /Donnager/FloodUI/config:/config
      - /Donnager/FloodUI/data0:/data
    ports:
      - "3001:3001"
    restart: unless-stopped 
