version: '3'
services:  
    flood:    
    hostname: flood    
    image: jesec/flood    
    user: 1000:1001    
    restart: unless-stopped    
    environment:      
        HOME: /config    
    volumes:      
        - /flood:/config      
        - /flood:/data    
    ports:      
        - 3001:3001
