version: '3'
services:  
    flood:    
    hostname: flood    
    image: jesec/flood    
    user: 1000:1001    
    restart: unless-stopped    
    command: --port 3001 --allowedpath /data    
    environment:      
        HOME: /config    
    volumes:      
        - /mnt/user/appdata/flood:/config      
        - /mnt/user/appdata/flood:/data    
    ports:      
        - 3001:3001    
    network_mode: bridge
