services:
  flood:
    build:
      context: .
      dockerfile: flood.dockerfile
    ports:
      - 3000:3000
    links:
      - rtorrent
    depends_on:
      - rtorrent
    environment:
      - RTORRENT_SOCK=true
      - NODE_ENV=development
      - FLOOD_SECRET=flood
    restart: always
    volumes:
      - ./downloads:/data/downloads
      - sock:/data

volumes:
  sock:
