version: "3.7"

services:
  jdownloader-2:
    container_name: jdownloader-2
    image: jlesage/jdownloader-2
    ports:
      - "5800:5800"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Kolkata
    volumes:
      - /Donnager/Jdownlaoder/config:/config
    restart: unless-stopped 
