version: "3.7"

services:
  jackett:
    container_name: jackett
    image: cr.hotio.dev/hotio/jackett
    ports:
      - "9117:9117"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Kolkata
    volumes:
      - /Donnager/Jackett/config:/config
    restart: unless-stopped 
