version: "3.7"

services:
  bazarr:
    container_name: bazarr
    image: cr.hotio.dev/hotio/bazarr
    ports:
      - "6767:6767"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Kolkata
    volumes:
      - /config/bazarr:/config
      - /mnt/bx1000:/mnt/bx1000
    restart: unless-stopped 
