version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "54:53/tcp"
      - "54:53/udp"
      - "801:80/tcp"
    environment:
      TZ: 'Asia/Kolkata'
      WEBPASSWORD: 'JD@27reddy'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
