version: '3.3'
services:
    server:
        container_name: vaultwarden
        restart: unless-stopped
        volumes:
            - '/vw-data/:/data/'
        ports:
            - '80:80'
        image: 'vaultwarden/server:latest'